[package]
name = "compiles"
version = "0.1.0"
authors = ["Kristoffer Ström <kristoffer@dusk.network>"]
edition = "2018"
description = "Check if micorkelvin compiles successfully to wasm"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dusk-abi = "0.9.0-rc"
microkelvin = { path = "../.." }
